-- Juniper & Stone table ordering starter schema.
-- Run once in Supabase SQL Editor. Keep the service_role key out of config.js.

begin;

create table if not exists public.restaurant_settings (
  id boolean primary key default true check (id),
  restaurant_name text not null default 'Juniper & Stone',
  phone text not null default '',
  address text not null default '',
  gstin text not null default '',
  logo_url text not null default '',
  offer_message text not null default 'Hi! A little treat from {business}: we have something special for you.',
  opening_hours text not null default '11 am – 11 pm',
  estimated_time text not null default '15–25 min',
  is_accepting_orders boolean not null default true,
  tax_percent numeric(6, 3) not null default 0 check (tax_percent >= 0 and tax_percent <= 100),
  currency text not null default 'INR' check (char_length(currency) = 3),
  upi_id text not null default '',
  bill_footer text not null default 'Thank you for dining with us.',
  is_delivery_enabled boolean not null default false,
  delivery_city text not null default '',
  delivery_areas text[] not null default '{}',
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  updated_at timestamptz not null default now()
);

alter table public.restaurant_settings add column if not exists gstin text not null default '';
alter table public.restaurant_settings add column if not exists opening_hours text not null default '11 am – 11 pm';
alter table public.restaurant_settings add column if not exists is_accepting_orders boolean not null default true;
alter table public.restaurant_settings add column if not exists logo_url text not null default '';
alter table public.restaurant_settings add column if not exists offer_message text not null default 'Hi! A little treat from {business}: we have something special for you.';
alter table public.restaurant_settings add column if not exists estimated_time text not null default '15–25 min';
alter table public.restaurant_settings add column if not exists is_delivery_enabled boolean not null default false;
alter table public.restaurant_settings add column if not exists delivery_city text not null default '';
alter table public.restaurant_settings add column if not exists delivery_areas text[] not null default '{}';
alter table public.restaurant_settings add column if not exists delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0);

create table if not exists public.menu_categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  position integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.menu_categories(id) on delete restrict,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  discount_percent numeric(5, 2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  is_today_special boolean not null default false,
  is_vegetarian boolean not null default true,
  is_available boolean not null default true,
  image_url text,
  tag text not null default '',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.menu_items add column if not exists discount_percent numeric(5, 2) not null default 0 check (discount_percent >= 0 and discount_percent <= 100);
alter table public.menu_items add column if not exists is_today_special boolean not null default false;

create table if not exists public.dining_tables (
  id uuid primary key default gen_random_uuid(),
  table_number text not null unique,
  qr_token text not null unique default gen_random_uuid()::text,
  capacity integer not null default 2 check (capacity > 0 and capacity <= 30),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  table_id uuid references public.dining_tables(id) on delete set null,
  order_type text not null default 'dine_in' check (order_type in ('dine_in', 'takeaway', 'delivery')),
  customer_name text,
  customer_phone text,
  marketing_opt_in boolean not null default false,
  customer_note text,
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  discount_total numeric(10, 2) not null default 0 check (discount_total >= 0),
  delivery_city text,
  delivery_area text,
  delivery_address text,
  delivery_postal_code text,
  delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0),
  tax_total numeric(10, 2) not null default 0 check (tax_total >= 0),
  grand_total numeric(10, 2) not null check (grand_total >= 0),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'preparing', 'ready', 'served', 'cancelled')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'paid')),
  payment_method text,
  public_token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists marketing_opt_in boolean not null default false;
alter table public.orders add column if not exists discount_total numeric(10, 2) not null default 0 check (discount_total >= 0);
alter table public.orders add column if not exists delivery_city text;
alter table public.orders add column if not exists delivery_area text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists delivery_postal_code text;
alter table public.orders add column if not exists delivery_fee numeric(10, 2) not null default 0 check (delivery_fee >= 0);
alter table public.orders drop constraint if exists orders_order_type_check;
alter table public.orders add constraint orders_order_type_check check (order_type in ('dine_in', 'takeaway', 'delivery'));

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  name text not null,
  price_at_order numeric(10, 2) not null check (price_at_order >= 0),
  list_price_at_order numeric(10, 2) not null default 0 check (list_price_at_order >= 0),
  discount_percent_at_order numeric(5, 2) not null default 0 check (discount_percent_at_order >= 0 and discount_percent_at_order <= 100),
  discount_amount numeric(10, 2) not null default 0 check (discount_amount >= 0),
  is_today_special_at_order boolean not null default false,
  quantity integer not null check (quantity between 1 and 20),
  is_vegetarian boolean not null default true
);

alter table public.order_items add column if not exists list_price_at_order numeric(10, 2) not null default 0 check (list_price_at_order >= 0);
alter table public.order_items add column if not exists discount_percent_at_order numeric(5, 2) not null default 0 check (discount_percent_at_order >= 0 and discount_percent_at_order <= 100);
alter table public.order_items add column if not exists discount_amount numeric(10, 2) not null default 0 check (discount_amount >= 0);
alter table public.order_items add column if not exists is_today_special_at_order boolean not null default false;

create table if not exists public.staff_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('owner', 'manager', 'staff')),
  display_name text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists menu_items_category_available_idx on public.menu_items(category_id, is_available, position);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_status_created_idx on public.orders(status, created_at desc);
create index if not exists orders_table_id_idx on public.orders(table_id);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists menu_items_touch_updated_at on public.menu_items;
create trigger menu_items_touch_updated_at before update on public.menu_items
for each row execute function public.touch_updated_at();
drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at before update on public.orders
for each row execute function public.touch_updated_at();
drop trigger if exists settings_touch_updated_at on public.restaurant_settings;
create trigger settings_touch_updated_at before update on public.restaurant_settings
for each row execute function public.touch_updated_at();

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select exists (
    select 1 from public.staff_users s
    where s.user_id = (select auth.uid()) and s.is_active = true
  );
$$;

create or replace function public.get_table_info(p_table_token text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object('table_number', t.table_number, 'is_active', t.is_active)
  from public.dining_tables t
  where t.qr_token = p_table_token and t.is_active = true
  limit 1;
$$;

create or replace function public.get_order_status(p_public_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object('status', o.status, 'order_number', o.order_number, 'updated_at', o.updated_at)
  from public.orders o
  where o.public_token = p_public_token
  limit 1;
$$;

drop function if exists public.create_order(text, text, text, jsonb, text);
drop function if exists public.create_order(text, text, text, boolean, text, jsonb, text);
drop function if exists public.create_order(text, text, text, boolean, text, jsonb, text, jsonb);

create or replace function public.create_order(
  p_table_token text,
  p_customer_name text,
  p_customer_phone text,
  p_marketing_opt_in boolean,
  p_customer_note text,
  p_items jsonb,
  p_order_type text default 'dine_in',
  p_delivery_details jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_table_id uuid;
  v_order_type text := coalesce(p_order_type, 'dine_in');
  v_order_id uuid;
  v_order_number bigint;
  v_public_token uuid;
  v_item jsonb;
  v_menu_item public.menu_items%rowtype;
  v_qty integer;
  v_item_count integer := 0;
  v_subtotal numeric(10, 2) := 0;
  v_tax_percent numeric(6, 3) := 0;
  v_tax numeric(10, 2) := 0;
  v_total numeric(10, 2) := 0;
  v_discount_percent numeric(5, 2) := 0;
  v_unit_discount numeric(10, 2) := 0;
  v_discount_total numeric(10, 2) := 0;
  v_is_accepting_orders boolean;
  v_delivery_enabled boolean;
  v_delivery_city text;
  v_delivery_areas text[];
  v_delivery_fee numeric(10, 2) := 0;
  v_input_city text;
  v_input_area text;
  v_input_address text;
  v_input_postal_code text;
begin
  select coalesce(s.is_accepting_orders, true) into v_is_accepting_orders
  from public.restaurant_settings s where s.id = true;
  if coalesce(v_is_accepting_orders, true) = false then
    raise exception 'The restaurant is not accepting orders right now.' using errcode = '22023';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Choose between 1 and 30 menu items.' using errcode = '22023';
  end if;
  if jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 30 then
    raise exception 'Choose between 1 and 30 menu items.' using errcode = '22023';
  end if;
  if v_order_type not in ('dine_in', 'delivery') then
    raise exception 'Invalid order type.' using errcode = '22023';
  end if;
  if v_order_type = 'dine_in' then
    select t.id into v_table_id from public.dining_tables t
    where t.qr_token = p_table_token and t.is_active = true;
    if v_table_id is null then
      raise exception 'This table QR is not active. Please ask a team member.' using errcode = '22023';
    end if;
  elsif v_order_type = 'delivery' then
    select coalesce(s.is_delivery_enabled, false), coalesce(s.delivery_city, ''), coalesce(s.delivery_areas, '{}'::text[]), coalesce(s.delivery_fee, 0)
    into v_delivery_enabled, v_delivery_city, v_delivery_areas, v_delivery_fee
    from public.restaurant_settings s where s.id = true;
    if not coalesce(v_delivery_enabled, false) or length(trim(v_delivery_city)) = 0 or cardinality(v_delivery_areas) = 0 then
      raise exception 'Home delivery is not available right now.' using errcode = '22023';
    end if;
    if p_delivery_details is null or jsonb_typeof(p_delivery_details) <> 'object' then
      raise exception 'Enter a delivery address in a supported area.' using errcode = '22023';
    end if;
    v_input_city := nullif(trim(p_delivery_details->>'city'), '');
    v_input_area := nullif(trim(p_delivery_details->>'area'), '');
    v_input_address := nullif(trim(p_delivery_details->>'address'), '');
    v_input_postal_code := nullif(trim(p_delivery_details->>'postal_code'), '');
    if lower(coalesce(v_input_city, '')) <> lower(trim(v_delivery_city)) then
      raise exception 'Delivery is only available in %.', v_delivery_city using errcode = '22023';
    end if;
    if v_input_area is null or not exists (select 1 from unnest(v_delivery_areas) as zones(area) where lower(trim(area)) = lower(v_input_area)) then
      raise exception 'Choose one of the supported delivery areas.' using errcode = '22023';
    end if;
    if v_input_address is null or length(v_input_address) > 300 or length(coalesce(v_input_postal_code, '')) > 12 then
      raise exception 'Enter a valid delivery address.' using errcode = '22023';
    end if;
    select trim(area) into v_input_area from unnest(v_delivery_areas) as zones(area) where lower(trim(area)) = lower(v_input_area) limit 1;
    v_input_city := trim(v_delivery_city);
  end if;
  if length(coalesce(p_customer_name, '')) > 80 or length(coalesce(p_customer_phone, '')) > 25 or length(coalesce(p_customer_note, '')) > 400 then
    raise exception 'Name or order note is too long.' using errcode = '22023';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    if jsonb_typeof(v_item) <> 'object' or not (v_item ? 'menu_item_id') or not (v_item ? 'quantity') then
      raise exception 'Every item needs a menu item and quantity.' using errcode = '22023';
    end if;
    v_qty := (v_item->>'quantity')::integer;
    if v_qty is null or v_qty < 1 or v_qty > 20 then
      raise exception 'Each quantity must be between 1 and 20.' using errcode = '22023';
    end if;
    select m.* into v_menu_item from public.menu_items m
    join public.menu_categories c on c.id = m.category_id and c.is_active = true
    where m.id = (v_item->>'menu_item_id')::uuid and m.is_available = true;
    if not found then
      raise exception 'A selected item is unavailable. Refresh the menu and try again.' using errcode = '22023';
    end if;
    v_discount_percent := coalesce(v_menu_item.discount_percent, 0);
    v_unit_discount := round(v_menu_item.price * v_discount_percent / 100, 2);
    v_subtotal := v_subtotal + ((v_menu_item.price - v_unit_discount) * v_qty);
    v_discount_total := v_discount_total + (v_unit_discount * v_qty);
    v_item_count := v_item_count + 1;
  end loop;
  if v_item_count <> jsonb_array_length(p_items) then
    raise exception 'One or more items could not be added.' using errcode = '22023';
  end if;

  select coalesce(s.tax_percent, 0) into v_tax_percent
  from public.restaurant_settings s where s.id = true;
  v_tax := round(v_subtotal * coalesce(v_tax_percent, 0) / 100, 2);
  v_total := v_subtotal + v_tax + v_delivery_fee;

  insert into public.orders (table_id, order_type, customer_name, customer_phone, marketing_opt_in, customer_note, subtotal, discount_total, tax_total, delivery_city, delivery_area, delivery_address, delivery_postal_code, delivery_fee, grand_total)
  values (v_table_id, v_order_type, nullif(trim(p_customer_name), ''), nullif(trim(p_customer_phone), ''), coalesce(p_marketing_opt_in, false) and nullif(trim(p_customer_phone), '') is not null, nullif(trim(p_customer_note), ''), v_subtotal, v_discount_total, v_tax, v_input_city, v_input_area, v_input_address, v_input_postal_code, v_delivery_fee, v_total)
  returning id, order_number, public_token into v_order_id, v_order_number, v_public_token;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_qty := (v_item->>'quantity')::integer;
    select m.* into v_menu_item from public.menu_items m
    join public.menu_categories c on c.id = m.category_id and c.is_active = true
    where m.id = (v_item->>'menu_item_id')::uuid and m.is_available = true;
    v_discount_percent := coalesce(v_menu_item.discount_percent, 0);
    v_unit_discount := round(v_menu_item.price * v_discount_percent / 100, 2);
    insert into public.order_items (order_id, menu_item_id, name, price_at_order, list_price_at_order, discount_percent_at_order, discount_amount, is_today_special_at_order, quantity, is_vegetarian)
    values (v_order_id, v_menu_item.id, v_menu_item.name, v_menu_item.price - v_unit_discount, v_menu_item.price, v_discount_percent, v_unit_discount * v_qty, v_menu_item.is_today_special, v_qty, v_menu_item.is_vegetarian);
  end loop;

  return jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'public_token', v_public_token,
    'subtotal', v_subtotal,
    'discount_total', v_discount_total,
    'tax_total', v_tax,
    'delivery_fee', v_delivery_fee,
    'grand_total', v_total,
    'status', 'pending'
  );
end;
$$;

alter table public.restaurant_settings enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.dining_tables enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.staff_users enable row level security;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
     ) then
    execute 'alter publication supabase_realtime add table public.orders';
  end if;
end;
$$;

drop policy if exists "Public can read restaurant settings" on public.restaurant_settings;
create policy "Public can read restaurant settings" on public.restaurant_settings
for select to anon, authenticated using (id = true);
drop policy if exists "Staff can update restaurant settings" on public.restaurant_settings;
create policy "Staff can update restaurant settings" on public.restaurant_settings
for update to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Public can read active categories" on public.menu_categories;
create policy "Public can read active categories" on public.menu_categories
for select to anon, authenticated using (is_active = true or public.is_staff());
drop policy if exists "Staff can manage categories" on public.menu_categories;
create policy "Staff can manage categories" on public.menu_categories
for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Public can read available dishes" on public.menu_items;
create policy "Public can read available dishes" on public.menu_items
for select to anon, authenticated using (is_available = true or public.is_staff());
drop policy if exists "Staff can manage menu" on public.menu_items;
create policy "Staff can manage menu" on public.menu_items
for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Staff can view dining tables" on public.dining_tables;
create policy "Staff can view dining tables" on public.dining_tables
for select to authenticated using (public.is_staff());
drop policy if exists "Staff can manage dining tables" on public.dining_tables;
create policy "Staff can manage dining tables" on public.dining_tables
for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Staff can view orders" on public.orders;
create policy "Staff can view orders" on public.orders
for select to authenticated using (public.is_staff());
drop policy if exists "Staff can update orders" on public.orders;
create policy "Staff can update orders" on public.orders
for update to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Staff can view order items" on public.order_items;
create policy "Staff can view order items" on public.order_items
for select to authenticated using (public.is_staff());
drop policy if exists "Staff can manage order items" on public.order_items;
create policy "Staff can manage order items" on public.order_items
for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists "Staff can see their own staff record" on public.staff_users;
create policy "Staff can see their own staff record" on public.staff_users
for select to authenticated using (user_id = (select auth.uid()));

grant usage on schema public to anon, authenticated;
grant select on public.restaurant_settings, public.menu_categories, public.menu_items to anon, authenticated;
grant update on public.restaurant_settings to authenticated;
grant insert, update, delete on public.menu_categories, public.menu_items, public.dining_tables, public.order_items to authenticated;
grant select on public.dining_tables, public.orders, public.order_items, public.staff_users to authenticated;
grant update (status, payment_status, payment_method) on public.orders to authenticated;
grant usage, select on sequence public.orders_order_number_seq to authenticated;

revoke all on function public.is_staff() from public;
revoke all on function public.get_table_info(text) from public;
revoke all on function public.get_order_status(uuid) from public;
revoke all on function public.create_order(text, text, text, boolean, text, jsonb, text, jsonb) from public;
grant execute on function public.is_staff() to anon, authenticated;
grant execute on function public.get_table_info(text) to anon, authenticated;
grant execute on function public.get_order_status(uuid) to anon, authenticated;
grant execute on function public.create_order(text, text, text, boolean, text, jsonb, text, jsonb) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('restaurant-assets', 'restaurant-assets', true, 2097152, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "Public can read restaurant assets" on storage.objects;
create policy "Public can read restaurant assets" on storage.objects
for select to anon, authenticated using (bucket_id = 'restaurant-assets');
drop policy if exists "Staff can manage restaurant assets" on storage.objects;
create policy "Staff can manage restaurant assets" on storage.objects
for all to authenticated using (bucket_id = 'restaurant-assets' and (storage.foldername(name))[1] = 'logos' and public.is_staff())
with check (bucket_id = 'restaurant-assets' and (storage.foldername(name))[1] = 'logos' and public.is_staff());

insert into public.restaurant_settings (id) values (true) on conflict (id) do nothing;

insert into public.menu_categories (id, slug, name, position) values
  ('10000000-0000-4000-8000-000000000001', 'small-plates', 'Small plates', 1),
  ('10000000-0000-4000-8000-000000000002', 'from-the-kitchen', 'From the kitchen', 2),
  ('10000000-0000-4000-8000-000000000003', 'sides', 'Sides & greens', 3),
  ('10000000-0000-4000-8000-000000000004', 'something-sweet', 'Something sweet', 4),
  ('10000000-0000-4000-8000-000000000005', 'to-drink', 'To drink', 5)
on conflict (slug) do nothing;

insert into public.menu_items (id, category_id, name, description, price, is_vegetarian, tag, position, image_url) values
  ('20000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', 'Burrata & stone fruit', 'Creamy burrata, ripe peaches, basil oil, toasted sourdough.', 425, true, 'A guest favourite', 1, 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000002', '10000000-0000-4000-8000-000000000001', 'Crispy lotus stem', 'Tossed in a sweet chilli glaze with sesame and spring onion.', 295, true, 'Crunchy & bright', 2, 'https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000003', '10000000-0000-4000-8000-000000000001', 'Charred chicken skewers', 'Yoghurt-marinated, served with mint chutney and pickled onion.', 385, false, 'From the grill', 3, 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000004', '10000000-0000-4000-8000-000000000002', 'Wild mushroom risotto', 'Arborio rice, forest mushrooms, parmesan, a little patience.', 545, true, 'Comfort in a bowl', 1, 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000005', '10000000-0000-4000-8000-000000000002', 'Slow-braised lamb', 'Six-hour lamb shoulder, saffron rice, crispy shallots.', 695, false, 'Slow & lovely', 2, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000006', '10000000-0000-4000-8000-000000000002', 'Garden harvest bowl', 'Roasted seasonal vegetables, hummus, quinoa, herby tahini.', 475, true, 'Plant-powered', 3, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000007', '10000000-0000-4000-8000-000000000003', 'Little gem salad', 'Crisp leaves, pear, toasted walnut, honey mustard dressing.', 285, true, 'Fresh & crisp', 1, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000008', '10000000-0000-4000-8000-000000000003', 'Rosemary shoestring fries', 'Thin-cut, twice cooked, dusted with parmesan and rosemary.', 195, true, 'A little extra', 2, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000009', '10000000-0000-4000-8000-000000000004', 'Warm chocolate fondant', 'Dark chocolate, soft centre, vanilla bean ice cream.', 325, true, 'Best shared', 1, 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000010', '10000000-0000-4000-8000-000000000004', 'Mango & cardamom kulfi', 'Alphonso mango, toasted pistachio, a pinch of cardamom.', 245, true, 'Seasonal', 2, 'https://images.unsplash.com/photo-1488900128323-21503983a07e?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000005', 'House lemonade', 'Fresh lime, a little mint, just the right amount of fizz.', 145, true, 'House-made', 1, 'https://images.unsplash.com/photo-1513558161293-cdaf765edfd7?auto=format&fit=crop&w=420&q=80'),
  ('20000000-0000-4000-8000-000000000012', '10000000-0000-4000-8000-000000000005', 'Cold brew coffee', 'Slow-steeped overnight, served over ice with oat milk.', 185, true, 'Slow mornings', 2, 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=420&q=80')
on conflict (id) do nothing;

insert into public.dining_tables (table_number, capacity)
select lpad(n::text, 2, '0'), case when n <= 4 then 2 else 4 end
from generate_series(1, 8) as g(n)
on conflict (table_number) do nothing;

commit;
